import { writable } from 'svelte/store';


export const fetchedData = writable({
    nodes: [],
    links: []
})

export const predicates = writable([])

export const selectedPredicates = writable([])

export const predicateLabels = {
    "http://dbpedia.org/property/name": "name",
    "http://dbpedia.org/ontology/birthPlace": "birth place",
    "http://dbpedia.org/property/birthPlace": "birth place",
    "http://dbpedia.org/ontology/birthDate": "birth date",
    "http://dbpedia.org/ontology/wikiPageID": "Wikipage page ID",
    "http://dbpedia.org/ontology/wikiPageRevisionID": "Wikipage revision ID",
    "http://dbpedia.org/ontology/wikiPageWikiLink": "Link from a Wikipage to another Wikipage",
    "http://dbpedia.org/ontology/wikiPageExternalLink": "Link from a Wikipage to an external page",
    "http://dbpedia.org/ontology/wikiPageRedirects": "Wikipage redirect",
    "http://dbpedia.org/ontology/wikiPageDisambiguates": "Wikipage disambiguates",
    "http://dbpedia.org/property/topGoalscorer": "top goalscorer",
    "http://dbpedia.org/property/youngestScorerPlayer": "youngest scorer player",
    "http://dbpedia.org/property/youthclubs": "youthclubs",
    "http://dbpedia.org/property/youthyears": "youthyears",
    "http://dbpedia.org/ontology/thumbnail": "thumbnail",
    "http://dbpedia.org/property/after": "after",
    "http://dbpedia.org/property/align": "align",
    "http://dbpedia.org/property/b": "b",
    "http://dbpedia.org/property/bg": "bg",
    "http://dbpedia.org/property/birthDate": "birth date",
    "http://dbpedia.org/property/captain": "captain",
    "http://dbpedia.org/property/caption": "caption",
    "http://dbpedia.org/property/d": "d",
    "http://dbpedia.org/property/direction": "direction",
    "http://dbpedia.org/property/fullname": "fullname",
    "http://dbpedia.org/property/goals": "goals",
    "http://dbpedia.org/property/height": "height",
    "http://dbpedia.org/property/image": "image",
    "http://dbpedia.org/property/lcf": "LCF",
    "http://dbpedia.org/property/n": "n",
    "http://dbpedia.org/property/namedafter": "namedafter",
    "http://dbpedia.org/property/p": "p",
    "http://dbpedia.org/property/player": "Player",
    "http://dbpedia.org/property/position": "position",
    "http://dbpedia.org/property/quote": "quote",
    "http://dbpedia.org/property/s": "s",
    "http://dbpedia.org/property/source": "source",
    "http://dbpedia.org/property/starring": "starring",
    "http://dbpedia.org/property/title": "title",
    "http://dbpedia.org/property/topScorer": "top scorer",
    "http://dbpedia.org/property/v": "v",
    "http://dbpedia.org/property/width": "width",
    "http://dbpedia.org/property/wikt": "wikt",
    "http://dbpedia.org/property/years": "years",
    "http://dbpedia.org/property/manOfTheMatch1a": "man of the match1a",
    "http://dbpedia.org/property/manOfTheMatch1b": "man of the match1b",
    "http://dbpedia.org/property/leagueTopscorer": "league topscorer",
    "http://dbpedia.org/property/seasonTopscorer": "season topscorer",
    "http://dbpedia.org/property/topGoalScorer": "top goal scorer",
    "http://dbpedia.org/property/caps": "caps",
    "http://dbpedia.org/ontology/abstract": "has abstract",
    "http://dbpedia.org/property/motm": "motm",
    "http://dbpedia.org/property/bordercolor": "bordercolor",
    "http://dbpedia.org/property/bracesPlayer": "braces player",
    "http://dbpedia.org/property/clubUpdate": "club-update",
    "http://dbpedia.org/property/clubnumber": "clubnumber",
    "http://dbpedia.org/property/clubs": "clubs",
    "http://dbpedia.org/property/currentclub": "currentclub",
    "http://dbpedia.org/property/fg": "fg",
    "http://dbpedia.org/property/hatTricksPlayer": "hat-tricks player",
    "http://dbpedia.org/property/mostAssistsPlayer": "most assists-player",
    "http://dbpedia.org/property/mostCaps": "Most caps",
    "http://dbpedia.org/property/mostConvertedFreeKicksPlayer": "most converted free kicks-player",
    "http://dbpedia.org/property/mostGoalsAssistsPlayer": "most goals assists-player",
    "http://dbpedia.org/property/mostPlayerAppearances": "most player appearances",
    "http://dbpedia.org/property/nationalcaps": "nationalcaps",
    "http://dbpedia.org/property/nationalgoals": "nationalgoals",
    "http://dbpedia.org/property/nationalteam": "nationalteam",
    "http://dbpedia.org/property/nationalteamUpdate": "nationalteam-update",
    "http://dbpedia.org/property/nationalyears": "nationalyears",
    "http://dbpedia.org/property/penaltiesMissedPlayer": "penalties missed-player",
    "http://dbpedia.org/property/penaltiesScoredPlayer": "penalties scored-player",
    "http://dbpedia.org/ontology/careerStation": "career station",
    "http://dbpedia.org/ontology/Person/height": "height (cm)",
    "http://dbpedia.org/ontology/wikiPageLength": "page length (characters) of wiki page",
    "http://dbpedia.org/ontology/height": "height (μ)",
    "http://dbpedia.org/ontology/number": "number",
    "http://dbpedia.org/ontology/currentMember": "current member",
    "http://dbpedia.org/ontology/keyPerson": "key person",
    "http://dbpedia.org/ontology/position": "position",
    "http://dbpedia.org/ontology/starring": "starring",
    "http://dbpedia.org/ontology/team": "team",
    "http://schema.org/sameAs": "sameAs"
    // Add more predicates and labels here
};